name: things_todo
description: A new Flutte r  project.

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.5 <3.0.0"
dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  hive: ^2.2.3
  image_picker: ^0.8.6
  intl: ^0.17.0
  nb_utils: ^4.6.25
  responsive_framework: ^0.2.0
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
  uses-material-design: true
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: assets/l10n
  output_dir: lib/generated
